
  
  window.webSnake = {};

  window.webSnake.urlMap = [
  {
    "oldUrl": "https://www.google.com/xjs/_/js/md=3/k=xjs.s.en_GB.rEwe7oIRWhk.O/ck=xjs.s.0QjRYUifokw.L.W.O/am=ChAAAAIEAAAAAAAAAAAAAAgAAAAAICogHALYAAH4yz0AQAAQAAABKYpCEAwAQMDnvyEEAkAAAEyAwAIwBBAVfswDAEgCVQB2AAAAgGG_iAAAABAAAIABQPgQoKEIDiAEVAICAAAAyAOA5wEEBhEWAAAAAAAAAAAAAAhggmBwQHq8IAACAAAAAAAAAAAAAFLS5OVAAgBq/rs=ACT90oGbgSaHVGbCz51cS5xy5rhrWJSmhw?cb=72433544",
    "newUrl": "module-graph.json"
  },
  {
    "oldUrl": "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.rEwe7oIRWhk.O/ck=xjs.s.0QjRYUifokw.L.W.O/am=ChAAAAIEAAAAAAAAAAAAAAgAAAAAICogHALYAAH4yz0AQAAQAAABKYpCEAwAQMDnvyEEAkAAAEyAwAIwBBAVfswDAEgCVQB2AAAAgGG_iAAAABAAAIABQPgQoKEIDiAEVAICAAAAyAOA5wEEBhEWAAAAAAAAAAAAAAhggmBwQHq8IAACAAAAAAAAAAAAAFLS5OVAAgBq/d=1/exm=SNUn3,attn,cEt90b,cdos,csi,d,dtl0hd,eHDfl,gwc,hsm,jsa,mb4ZUb,qddgKe,sTsDMc/ed=1/dg=2/br=1/ujg=1/rs=ACT90oGbgSaHVGbCz51cS5xy5rhrWJSmhw/ee=AfeaP:TkrAjf;BMxAGc:E5bFse;BgS6mb:fidj5d;BjwMce:cXX2Wb;CxXAWb:YyRLvc;DULqB:RKfG5c;DpcR3d:zL72xf;EABSZ:MXZt9d;ESrPQc:mNTJvc;EVNhjf:pw70Gc;EmZ2Bf:zr1jrb;Erl4fe:FloWmf;F9mqte:UoRcbe;Fmv9Nc:O1Tzwc;G0KhTb:LIaoZ;G6wU6e:hezEbd;GleZL:J1A7Od;HMDDWe:G8QUdb;IBADCc:RYquRb;IoGlCf:b5lhvb;JXS8fb:Qj0suc;JsbNhc:Xd8iUd;KOxcK:bFOvTc;KQzWid:ZMKkN;KcokUb:KiuZBf;KpRAue:Tia57b;LBgRLc:SdcwHb,XVMNvd;LEikZe:byfTOb,lsjVmc;LsNahb:ucGLNb;Me32dd:MEeYgc;NPKaK:SdcwHb;NSEoX:lazG7b;Np8Qkd:Dpx6qc;Nyt6ic:jn2sGd;OgagBe:cNTe0;Oj465e:KG2eXe;Pjplud:EEDORb,PoEs9b;PqHfGe:im2cZe;Q1Ow7b:x5CSu;QGR0gd:Mlhmy;R2kc8b:ALJqWb;R4IIIb:QWfeKf;R9Ulx:CR7Ufe;SLtqO:Kh1xYe;SMDL4c:fTfGO,pnvXVc;SNUn3:ZwDk9d,x8cHvb;ShpF6e:N0pvGc;TxfV6d:YORN0b;U96pRd:FsR04;UDrY1c:eps46d;UVmjEd:EesRsb;UyG7Kb:wQd0G;V2HTTe:RolTY;VGRfx:VFqbr;VN6jIc:ddQyuf;VOcgDe:YquhTb;VxQ32b:k0XsBb;WCEKNd:I46Hvd;WDGyFe:jcVOxd;Wfmdue:g3MJlb;XUezZ:sa7lqb;YV5bee:IvPZ6d;ZWEUA:afR4Cf;a56pNe:JEfCwb;aAJE9c:WHW6Ef;aZ61od:arTwJ;bFZ6gf:RsDQqe;bcPXSc:gSZLJb;cEt90b:ws9Tlc;cFTWae:gT8qnd;coJ8e:KvoW8;dIoSBb:ZgGg9b;dLlj2:Qqt3Gf;daB6be:lMxGPd;dtl0hd:lLQWFe;eBAeSb:Ck63tb;eBZ5Nd:audvde;eHDfl:ofjVkb;eO3lse:nFClrf;g8nkx:U4MzKc;gaub4:TN6bMe;gtVSi:ekUOYd;h3MYod:cEt90b;hK67qb:QWEO5b;heHB1:sFczq;hjRo6e:F62sG;iFQyKf:QIhFr,vfuNJf;imqimf:jKGL2e;io8t5d:sgY6Zb;jY0zg:zmptHf;k2Qxcb:XY51pe;kCQyJ:ueyPK;kMFpHd:OTA3Ae;kY7VAf:d91TEb;kbAm9d:MkHyGd;lkq0A:JyBE3e;lzgfYb:PI40bd;nAFL3:NTMZac,s39S4;oGtAuc:sOXFj;oSUNyd:fTfGO,pnvXVc;oUlnpc:RagDlc;okUaUd:wItadb;pKJiXd:VCenhc;pNsl2d:j9Yuyc;pXdRYb:JKoKVe;pj82le:mg5CW;qGV2uc:HHi04c;qZx2Fc:j0xrE;qaS3gd:yiLg6e;qavrXe:mYbt1d,zQzcXe;qddgKe:d7YSfd,x4FYXe;rQSrae:C6D5Fc;sP4Vbe:VwDzFe;sTsDMc:kHVSUb;tH4IIe:Ymry6;tosKvd:ZCqP3;trZL0b:qY8PFe;uY49fb:COQbmf;uknmt:GkPrzb;uuQkY:u2V3ud;vfVwPd:lcrkwe;w3bZCb:ZPGaIb;w4rSdf:XKiZ9;w9w86d:dt4g2b;wQlYve:aLUfP;wR5FRb:O1Gjze,TtcOte;wV5Pjc:L8KGxe;whEZac:F4AmNb;xBbsrc:NEW1Qc;xbe2wc:wbTLEd;yGxLoc:FmAr0c;yxTchf:KUM7Z;z97YGf:oug9te;zOsCQe:Ko78Df;zaIgPb:Qtpxbd/m=pHXghd,pKhWu?cb=72433544&xjs=s1",
    "newUrl": "snake.js"
  },
  {
    "oldUrl": "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.rEwe7oIRWhk.O/am=CgAAAAIAAAAAAAAAAAAAAAgAAAAAICoAAAIAAAFowx0AQAAQAAABKYpCEAwAQMDnvyEEAkAAAEwAwAIQBAAUAMwDAAgAVAAAAAAAgGG_CAAAAAAAAIABQPgAICEADiAEVAICAAAAyAOA5wEEBhEWAAAAAAAAAAAAAAhggmBwQHq8IAACAAAAAAAAAAAAAFLS5OVAAgBq/d=1/ed=1/dg=2/br=1/rs=ACT90oEHIPVhNvQBQ-LW1p-M-9g3S99svw/ee=cEt90b:ws9Tlc;qddgKe:x4FYXe,d7YSfd;yxTchf:KUM7Z;dtl0hd:lLQWFe;eHDfl:ofjVkb;qaS3gd:yiLg6e;nAFL3:NTMZac,s39S4;oGtAuc:sOXFj;iFQyKf:vfuNJf,QIhFr;SNUn3:ZwDk9d,x8cHvb;io8t5d:sgY6Zb;Oj465e:KG2eXe,KG2eXe;Erl4fe:FloWmf,FloWmf;JsbNhc:Xd8iUd;sP4Vbe:VwDzFe;kMFpHd:OTA3Ae;uY49fb:COQbmf;Pjplud:PoEs9b,EEDORb;QGR0gd:Mlhmy;a56pNe:JEfCwb;Me32dd:MEeYgc;wR5FRb:TtcOte,O1Gjze;pXdRYb:JKoKVe;dIoSBb:ZgGg9b;EmZ2Bf:zr1jrb;NSEoX:lazG7b;eBAeSb:Ck63tb;WCEKNd:I46Hvd;wV5Pjc:L8KGxe;EVNhjf:pw70Gc;sTsDMc:kHVSUb;wQlYve:aLUfP;zOsCQe:Ko78Df;KcokUb:KiuZBf;YV5bee:IvPZ6d;kbAm9d:MkHyGd;ZWEUA:afR4Cf;g8nkx:U4MzKc;qZx2Fc:j0xrE;lzgfYb:PI40bd;w9w86d:dt4g2b;GleZL:J1A7Od;bcPXSc:gSZLJb;JXS8fb:Qj0suc;IoGlCf:b5lhvb;VN6jIc:ddQyuf;vfVwPd:lcrkwe;xBbsrc:NEW1Qc;pNsl2d:j9Yuyc;VGRfx:VFqbr;BjwMce:cXX2Wb;ESrPQc:mNTJvc;R9Ulx:CR7Ufe;kY7VAf:d91TEb;NPKaK:SdcwHb;LBgRLc:XVMNvd,SdcwHb;UyG7Kb:wQd0G;LsNahb:ucGLNb;KpRAue:Tia57b;jY0zg:zmptHf;coJ8e:KvoW8;oSUNyd:fTfGO,fTfGO,pnvXVc;SMDL4c:fTfGO,pnvXVc;aZ61od:arTwJ;w4rSdf:XKiZ9;h3MYod:cEt90b;eO3lse:nFClrf;zaIgPb:Qtpxbd;HMDDWe:G8QUdb;ShpF6e:N0pvGc;k2Qxcb:XY51pe;IBADCc:RYquRb;pKJiXd:VCenhc;rQSrae:C6D5Fc;kCQyJ:ueyPK;EABSZ:MXZt9d;qavrXe:zQzcXe,mYbt1d;TxfV6d:YORN0b;UDrY1c:eps46d;F9mqte:UoRcbe;Nyt6ic:jn2sGd;w3bZCb:ZPGaIb;G0KhTb:LIaoZ;XUezZ:sa7lqb;aAJE9c:WHW6Ef;V2HTTe:RolTY;Wfmdue:g3MJlb;imqimf:jKGL2e;BgS6mb:fidj5d;gtVSi:ekUOYd;KQzWid:ZMKkN;UVmjEd:EesRsb;z97YGf:oug9te;AfeaP:TkrAjf;eBZ5Nd:audvde;CxXAWb:YyRLvc;OgagBe:cNTe0;SLtqO:Kh1xYe;tosKvd:ZCqP3;VOcgDe:YquhTb;uuQkY:u2V3ud;WDGyFe:jcVOxd;trZL0b:qY8PFe;VxQ32b:k0XsBb;DULqB:RKfG5c;Np8Qkd:Dpx6qc;cFTWae:gT8qnd;gaub4:TN6bMe;DpcR3d:zL72xf;hjRo6e:F62sG;yGxLoc:FmAr0c;pj82le:mg5CW;dLlj2:Qqt3Gf;qGV2uc:HHi04c;oUlnpc:RagDlc;R2kc8b:ALJqWb;Q1Ow7b:x5CSu;bFZ6gf:RsDQqe;okUaUd:wItadb;xbe2wc:wbTLEd;KOxcK:bFOvTc;G6wU6e:hezEbd;uknmt:GkPrzb;U96pRd:FsR04;PqHfGe:im2cZe;heHB1:sFczq;Fmv9Nc:O1Tzwc;hK67qb:QWEO5b;BMxAGc:E5bFse;R4IIIb:QWfeKf;whEZac:F4AmNb;tH4IIe:Ymry6;lkq0A:JyBE3e;daB6be:lMxGPd;LEikZe:byfTOb,lsjVmc/m=attn,cdos,gwc,hsm,jsa,mb4ZUb,d,csi,cEt90b,SNUn3,qddgKe,sTsDMc,dtl0hd,eHDfl?cb=72433544",
    "newUrl": "snake-loader.js"
  }
];
  
  window.webSnake.blockedUrls = [
    "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.rEwe7oIRWhk.O/am=CgAAAAIAAAAAAAAAAAAAAAgAAAAAICoAAAIAAAFowx0AQAAQAAABKYpCEAwAQMDnvyEEAkAAAEwAwAIQBAAUAMwDAAgAVAAAAAAAgGG_CAAAAAAAAIABQPgAICEADiAEVAICAAAAyAOA5wEEBhEWAAAAAAAAAAAAAAhggmBwQHq8IAACAAAAAAAAAAAAAFLS5OVAAgBq/d=0/dg=2/br=1/rs=ACT90oEHIPVhNvQBQ-LW1p-M-9g3S99svw/m=sb_wiz,aa,abd,syug,syvo,syuq,syus,syur,syup,syvp,syvs,syvr,syvt,syvx,syvy,syuv,syvk,syw7,syw8,syw9,syw2,syw3,syw5,syw6,syph,syuu,syw0,syvz,syw1,sywa,syf1,sywg,syvv,sywh,sywb,sywc,sywe,sywf,sywd,sywi,sywj,sywn,sywm,sy281,async,sy1gy,bgd,sy2jv,sy2jw,foot,sy2av,sy5j7,kyn,sy2il,lli,mu,sf,sy102,sy231,sy232,sy5l0,sonic,sybl,syfm,syfn,syu6,syu7,syu5,sytw,syv1,sy85,syav,syay,syaz,sy18r,sy18p,sy18q,syvf,syve,syvd,sy1cv,sy26n,syea,sy1c4,sy634,spch,tl?cb=72433544&xjs=s3"
];
  
  